name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Flutter pub get
        run: flutter pub get

      - name: Change CODE_SIGN_STYLE to Manual
        run: |
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Set iOS deployment target
        run: |
          cd ios
          if ! grep -q "platform :ios, '16.0'" Podfile; then
            echo "platform :ios, '16.0'" | cat - Podfile > temp && mv temp Podfile
          fi
          cd ..

      - name: Clean and update CocoaPods
        run: |
          rm -f ios/Podfile.lock
          cd ios
          pod repo update
          pod deintegrate
          pod install
          cd ..

      - name: Disable Code Signing
        run: |
          sed -i '' 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = "";/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_IDENTITY = .*/CODE_SIGN_IDENTITY = "";/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = .*/PROVISIONING_PROFILE_SPECIFIER = "";/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Build iOS (no signing)
        run: flutter build ios --release --no-codesign --no-tree-shake-icons

      - name: Create IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/FlutterIpaExport.ipa